module.exports = {
	singleQuote: true,
	semi: true,
	tabWidth: 2,
	useTabs: true,
	trailingComma: 'all',
	arrowParens: 'always',
	endOfLine: 'lf',
	bracketSpacing: true,
	proseWrap: 'preserve',
	plugins: [
		'prettier-plugin-svelte',
		'@ianvs/prettier-plugin-sort-imports',
		'prettier-plugin-tailwindcss',
	],
	importOrder: [
		'^\\$app/',
		'^svelte$',
		'^svelte-remixicon$',
		'',
		'^\\$lib/components/ui/',
		'^\\$lib/components/',
		'',
		'^\\$lib/js/',
		'^\\$lib/store/',
		'',
		'^[./]',
	],
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	overrides: [{ files: '*.svelte', options: { parser: 'svelte' } }],
};
